language: python
sudo: false
addons:
  apt:
    packages:
    - python-gdal
    - gdal-bin
    - fiona
    - python-dev
    - python3-dev

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

before_install:
  - pip install -U pip

install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - pip install -e .

script: 
  - py.test tests --doctest-modules --pep8 etl2osm -v --cov etl2osm --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    - carriere.denis@gmail.com