language: python
sudo: true
python:
  - "2.7"
  - "3.3"
  - "3.4"

cache:
  apt: true

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa && sudo apt-get update
  - sudo apt-get install -y gdal-bin
  - sudo apt-get install -y python-gdal
  - sudo apt-get install -y libgdal-dev
  - sudo pip install Fiona
  - sudo easy install GDAL
  - pip install -U pip

install:
  - "pip install -r requirements-dev.txt"
  - "pip install -r requirements.txt"
  - "pip install -e ."

script: 
  - py.test tests --doctest-modules --pep8 etl2osm -v --cov etl2osm --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    - carriere.denis@gmail.com
