language: python
sudo: true
addons:
  apt:
    packages:
    - python-gdal
    - gdal-bin
    - python-dev
    - python3-dev

python:
  - "2.7"
  - "3.3"
  - "3.4"

cache:
  apt: true

before_install:
  - sudo pip install Fiona
  - pip install -U pip

install:
  - "pip install -r requirements-dev.txt"
  - "pip install -r requirements.txt"
  - "pip install -e ."

script: 
  - py.test tests --doctest-modules --pep8 etl2osm -v --cov etl2osm --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    - carriere.denis@gmail.com
