language: python
sudo: false
addons:
  apt:
    packages:
    - python-gdal
    - gdal-bin
    - fiona
    - gcc-4.8
    - g++-4.8
    - libgdal1-dev

python:
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - pip install -U pip
  - pip install -r requirements-dev.txt
  - pip install fiona

install:
  - pip install -r requirements.txt
  - pip install -e .

script: 
  - py.test tests --doctest-modules --pep8 etl2osm -v --cov etl2osm --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    - carriere.denis@gmail.com