language: python
sudo: false
cache:
  directories:
    - $GDALINST
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels
    - GDALINST=$HOME/gdalinstall
    - GDALBUILD=$HOME/gdalbuild
  matrix:
    - GDALVERSION = "1.9.2"
    - GDALVERSION = "1.11.2"
      #- GDALVERSION = "2.0.1"

addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
    - libatlas-dev
    - libatlas-base-dev
    - gfortran

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

before_install:
  - pip install -U pip
  - pip install wheel

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gdal
  - . ./scripts/travis_gdal_install.sh
  - export PATH=$GDALINST/gdal-$GDALVERSION/bin:$PATH
  - export LD_LIBRARY_PATH=$GDALINST/gdal-$GDALVERSION/lib:$LD_LIBRARY_PATH

install:
  - pip wheel -r requirements-dev.txt
  - pip install -r requirements-dev.txt
  - pip install --upgrade --force-reinstall --global-option=build_ext --global-option='-I$GDALINST/gdal-$GDALVERSION/include' --global-option='-L$GDALINST/gdal-$GDALVERSION/lib' --global-option='-R$GDALINST/gdal-$GDALVERSION/lib' -e .
  - pip install coveralls
  - pip install -e .

script: 
  - py.test tests --doctest-modules --pep8 etl2osm -v --cov etl2osm --cov-report term-missing

after_success:
  - coveralls

notifications:
  email:
    - carriere.denis@gmail.com