sudo: true
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-gdal

install:
  - pip install -r requirements.txt
  - python setup.py develop

script:
  - py.test test_etl2osm.py

notifications:
  email:
    - carriere.denis@gmail.com